### ISSUE TITLE
Incorrect use of CString::from_vec_unchecked

### ISSUE THREAD

**Issue by chloekek** [sanpii/libpq.rs#24]
`CString::from_vec_unchecked` requires that the argument does not contain interior nuls.

The function `to_cstr` does not guard against interior nuls in the argument:

https://github.com/sanpii/libpq.rs/blob/9e161c365e1b921e31748e0eb159075b0e4d14e6/src/ffi.rs#L3-L5

This function is called on user input in several places, such as here:

https://github.com/sanpii/libpq.rs/blob/9e161c365e1b921e31748e0eb159075b0e4d14e6/src/connection/_exec.rs#L78-L79

Which means the safety requirement of `CString::from_vec_unchecked` can be violated by passing e.g. `"\0"` to `Connection::prepare`.

The function `new_cstring` likewise violates the safety requirement when given any non-zero argument.

**Comment by sanpii** [comment]
I don’t understand why `CString::from_vec_unchecked` has marked as unsafe, all called functions internally are safe.

Calling `Connection::exec` with a string containing a null bit work as expected:
```rust
fn main() {
    let conn = libpq::Connection::new("host=localhost").unwrap();
    let results = conn.exec("\0select 1;");
    assert_eq!(results.status(), libpq::Status::EmptyQuery);
}
```

The old behavior is to panic. From my point of view it seems less acceptable.

**Comment by iuridiniz** [comment]
According to [this](https://github.com/rust-lang/rust/issues/29918), this call is marked as unsafe due to a design contract and this not relate to memory safety: CString is guaranteed to not have interior nulls, as the documentation states that CString is ["A type representing an owned, C-compatible, nul-terminated string with no nul bytes in the middle."](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.from_vec_unchecked:~:text=A%20type%20representing%20an%20owned%2C%20C%2Dcompatible%2C%20nul%2Dterminated%20string%20with%20no%20nul%20bytes%20in%20the%20middle.)

IMHO, This clarification renders this issue safe to be closed.

**Comment by sanpii** [comment]
Thank you.
